<?php echo $this->doctype(); ?>
<style>
body{
    font-family: "Segoe UI",Arial,sans-serif;
}
.vertical-menu {
    width: 15%;
    float: left;
    position: relative;
}

.vertical-menu a {
    background-color: #eee;
    color: black;
    display: block;
    padding: 12px;
    text-decoration: none;
}

.vertical-menu a:hover {
    background-color: #ccc;
}

.vertical-menu a.active {
    background-color: #4CAF50;
    color: white;
}
body{
    padding-top: 0px !important;
}
.container{
    width: 100%;
}
.navbar{
    margin: 0px !important;
}
</style>


<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
    border-right:1px solid #bbb;
}

li:last-child {
    border-right: none;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
#contenedor{
    width: 100%;
    margin: 1% 0;
    display: inline-block;
}
.vertical-menu {
    width: 15%;
    float: left;
    position: relative;
}
#contentModul{
    width: 80%;
    position: relative;
    float: left;
    /* display: inline-block; */
    margin: 0 1%;
}
</style>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.0/sweetalert2.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.0/sweetalert2.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        
        <div id="menu-options">
            <ul>
                <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li class=""><a href="">Acerca</a></li>
                <li class=""><a href="">Servicios</a></li>
                <li class=""><a href="">Testimonios</a></li>
                <li class=""><a href="">Noticias</a></li>
                <li class=""><a href="">Contacto</a></li>
                <?php 
                    if (!isset($sesion)) {
                        echo "<li style='float:right;'><a href='#' style='float:right;'><span class='fa fa-user'></span> Sign Up</a></li>
                        <li><a href='#'><span class='fa fa-sign-in'></span> Login</a></li>";
                    }
                    else {
                        echo "<li style='float:right;'><a href='#' ><span class='fa fa-user'></span> ".$sesion['usuario']."</a></li><li  style='float:right;'><a href='/index/logout' ><span class='fa fa-sign-out'></span> Logout</a></li>";   
                    }
                ?>                        
            </ul>
        </div>

            <div id="contenedor">
                <div class="container-fluid">
                    <div class="vertical-menu">
                      <a id="pacientes" href="/citas/pacientes" class="menuOpt active">Pacientes</a>
                      <a id="agenda" href="/citas/agenda" class="menuOpt">Agenda</a>
                      <a id="editsitio" href="/citas/editsitio" class="menuOpt">Editar Sitio</a>
                      <a id="historial" href="/citas/historial" class="menuOpt">Historial</a>
                      <a id="notas" href="/citas/notas" class="menuOpt">Notas</a>
                      <a id="pagos" href="/citas/pagos" class="menuOpt">Pagos</a>
                      <a id="registros" href="/citas/registros" class="menuOpt">Registros</a>
                      <a id="usuarios" href="/citas/usuarios" class="menuOpt">Usuarios</a>
                    </div>
                    <div id="contentModul">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <script type="text/javascript">
            $("a.menuOpt").on('click', function(event){
                $("a.menuOpt.active").removeClass('active');
                $(this).addClass('active');
                // event.preventDefault();
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
