<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script type="text/javascript" src="/js/js/modales.js" async></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <!-- Page content -->
    <h1>Agenda</h1>

<script src="https://cdn.alloyui.com/3.0.1/aui/aui-min.js"></script>
<link href="https://cdn.alloyui.com/3.0.1/aui-css/css/bootstrap.min.css" rel="stylesheet"></link>

<div id="myScheduler"></div>


<script type="text/javascript">
	$(".vertical-menu > a.menuOpt.active").removeClass('active');
    $(".vertical-menu").find("a#agenda").addClass('active');

YUI().use(
  'aui-scheduler',
  function(Y) {
    var events = [
      {
        content: 'Partial Lunar Eclipse',
        endDate: new Date(2017, 11, 11, 5),
        startDate: new Date(2017, 11, 25, 1)
      },
      {
        color: "#8d8",
        content: 'Earth Day Lunch',
        disabled: true,
        endDate: new Date(2017, 11, 22, 13),
        meeting: true,
        reminder: true,
        startDate: new Date(2017, 11, 22, 12)
      },
      {
        content: "Weeklong",
        endDate: new Date(2017, 11, 27),
        startDate: new Date(2017, 11, 21)
      }
    ];

    var agendaView = new Y.SchedulerAgendaView();
    var dayView = new Y.SchedulerDayView();
    var weekView = new Y.SchedulerWeekView();
    var monthView = new Y.SchedulerMonthView();

    var eventRecorder = new Y.SchedulerEventRecorder();

    new Y.Scheduler(
      {
        activeView: weekView,
        boundingBox: '#myScheduler',
        date: new Date(2017, 11, 25),
        eventRecorder: eventRecorder,
        items: events,
        render: true,
        views: [dayView, weekView, monthView, agendaView]
      }
    );
  }
);
</script>