<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/citas.js"></script>
<style type="text/css">
	#barra-principal{
		display: inline-block;
		width: 100%;
		box-shadow: 0px 1px 2px #888;
		border-radius: 5px;
		padding: 5px;
	}
	#info-cliente{
		float: left;
		margin: 5px
	}
	#info-extra{
		float: left;
		margin: 5px
	}
	#info-hoy{
		float: left;
		margin: 5px
	}
	/* Contenido Panel principal */
	#contenido-panelprincipal{
		display: inline-block;
		width: 100%;
		box-shadow: 0px 1px 2px #888;
		border-radius: 5px;
		padding: 5px;
	}
	#noti-cita{
		float: left;
		margin: 5px
	}
	#btncitas-inicio{
		float: left;
		margin: 5px
	}
</style>

<h1>Panel Principal</h1>

<div id="barra-principal">
	<div id="info-cliente">Total de clientes</div>
	<div id="info-extra">Total de clientes</div>
	<div id="info-hoy">Total de clientes</div>
</div>

<div id="contenido-panelprincipal" id="contenido">
	<div id="notif-cita">Proxima Cita</div>
	<div id="btncitas-inicio"><a href="/citas/consultar" target="_blank">Iniciar consulta</div>
</div>

<script type="text/javascript">
    $(".vertical-menu > a.menuOpt.active").removeClass('active');
    $(".vertical-menu").find("a#panelprincipal").addClass('active');
</script>