<!DOCTYPE html>
<html>
<head>
<style>
/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
</style>
<!-- Modal -->
<style type="text/css">
	div#pestanas{
		width: 100%;
	}
	h1.pestanaOpt{
		margin: 0 5px;
	}
	#formulario{
		margin: 0 auto;
	}

	.activePest{
		display: none;
	}
	#pestanas{
		text-align: center;
		display: inline-block;
	}
	div.pestanaOpt{
		float: left;
		text-align: center;
		width: 50%;
	}
	.group-input{
		margin: 5px 0px;
	}
	.group-indiv > input,
	.group-indiv > button{
		width: 100%;
	}
	.activePestOpt{
		background: gray;
		width: 50%;
	}
</style>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.com/libraries/izimodal">
</head>
<body>
	<h1>Casdfa va2</h1>

	<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <div id="contentModal"></div>
  </div>

</div>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="text/javascript">
		$("#entrar").on("click", function(){
			$.ajax({
				method : 'POST',
				url : 'login',
				dataType : 'html',
				success: function(result){
					// console.log(result);
					$('#contentModal').html(result);
					$('#myModal').css('display', 'block');
					$("#usuario").focus();
				}
			});
			
			// Get the modal
			var modal = document.getElementById('myModal');

			// Get the button that opens the modal
			var btn = document.getElementById("myBtn");

			// Get the <span> element that closes the modal
			var span = document.getElementsByClassName("close")[0];

			// When the user clicks on <span> (x), close the modal
			span.onclick = function() {
			    modal.style.display = "none";
			}

			// When the user clicks anywhere outside of the modal, close it
			window.onclick = function(event) {
			    if (event.target == modal) {
			        modal.style.display = "none";
			    }
			}
		});

		function pestanaOpt(ctrl){
			console.log(this);
			var contenido = $(ctrl).attr("id");
			console.log(contenido);
			$(ctrl).parent().children().removeClass("activePestOpt");
			$(ctrl).addClass("activePestOpt");
			$("div.activePest").removeClass("activePest");
			$("." + contenido).addClass("activePest");
		}

		$(window).on('keydown', function(event){
			if(event.which == 13){
				if($("div#pest2").attr("class").toString().includes('activePestOpt')){
					$("#inciar").click();
				}
				if($("div#pest1").attr("class").toString().includes('activePestOpt')){
					$("#registro").click();	
				}
			}
		});
	</script>
</body>
</html>

